git:
  depth: false
  submodules: false
sudo: false
language: node_js
cache: yarn
node_js:
  - "10"
  - "8"
  - "6"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - yarn build

script:
  - yarn coverage --ci --maxWorkers=4 --no-cache

after_success:
  - yarn coverage-ci

stages:
  - lint
  - test
  - name: publish
    if: repo = babel/minify
      AND branch = master
      AND type = push

jobs:
  include:
    - stage: lint
      node_js: "10"
      script: yarn lint
    - stage: publish
      node_js: "10"
      script: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      deploy:
        provider: script
        script: npm run publish-master
        skip_cleanup: true
        on:
          condition: '! $TRAVIS_COMMIT_MESSAGE =~ \[skip\ publish\]'
