version: 2.1

aliases:
  - &restore-node-modules-cache
    keys:
      - v1-yarn-deps-{{ checksum "yarn.lock" }}
      - v1-yarn-deps-

  - &restore-yarn-cache
    keys:
      - v1-1-yarn-cache-{{ checksum "yarn.lock" }}
      - v1-1-yarn-cache-

  - &save-node-modules-cache
    paths:
      - node_modules
    key: v1-yarn-deps-{{ checksum "yarn.lock" }}

  - &save-yarn-cache
    paths:
      - ~/.cache/yarn
    key: v1-1-yarn-cache-{{ checksum "yarn.lock" }}

executors:
  node-executor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/babel/minify

jobs:
  build:
    executor: node-executor
    parallelism: 4
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: git submodule update --init --recursive
      - restore_cache: *restore-yarn-cache
      - restore_cache: *restore-node-modules-cache
      - run: yarn
      - run: yarn build
      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache
      - run: ./smoke/circleci.sh
